services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: habibi_secret
      MYSQL_DATABASE: webapp_db
      MYSQL_USER: admin_user
      MYSQL_PASSWORD: habibi_secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: habibi_secret

  forum-service:
    image:
      docker.io/library/forum-service:1.0-SNAPSHOT
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_DATABASE: webapp_db
      MYSQL_USER: admin_user
      MYSQL_PASSWORD: habibi_secret

  webapp:
    image:
      docker.io/library/webapp:1.0-SNAPSHOT
    restart: always
    ports:
      - "80:80"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_DATABASE: webapp_db
      MYSQL_USER: admin_user
      MYSQL_PASSWORD: habibi_secret


