services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mrcucumber1337
      MYSQL_DATABASE: web_lab_db
      MYSQL_USER: tokarev
      MYSQL_PASSWORD: mrcucumber1337

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: mrcucumber1337

  forum-service:
    image:
      docker.io/library/forum-service:0.0.1-SNAPSHOT
    restart: always
    environment:
      MYSQL_DATABASE: web_lab_db
      MYSQL_USER: tokarev
      MYSQL_PASSWORD: mrcucumber1337

  webapp:
    image:
      docker.io/library/webapp:0.0.1-SNAPSHOT
    restart: always
    ports:
      - "80:80"
    environment:
      MYSQL_DATABASE: web_lab_db
      MYSQL_USER: tokarev
      MYSQL_PASSWORD: mrcucumber1337


