services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: liljeep
      MYSQL_DATABASE: forumapp_db
      MYSQL_USER: gen_user
      MYSQL_PASSWORD: liljeep

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: liljeep

  forum-service:
    image:
      81911fa5-polite-trinculo.registry.twcstorage.ru/forumapp/forum-service
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_DATABASE: forumapp_db
      MYSQL_USER: gen_user
      MYSQL_PASSWORD: liljeep

  webapp:
    image:
      81911fa5-polite-trinculo.registry.twcstorage.ru/forumapp/webapp
    restart: always
    ports:
      - "80:80"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_DATABASE: forumapp_db
      MYSQL_USER: gen_user
      MYSQL_PASSWORD: liljeep

